reference:
    dummy_ref.txt
tags:
    ../test_data/tags_no_CAA.txt
heel:
    ../test_data/heel.txt

forward:
    ../test_data/first_100k_R1.fastq
reverse:
    ../test_data/first_100k_R2.fastq

# alternatively:
unpairedfastq:
    ../test_data/first_100k_R1.fastq

pairedparams:
    7:5:10
outprefix:
    test_
h5score:
    0.9
h3score:
    0.9
filtering:
    1:50:150:20:15
gsp:
    ../test_data/tabulated_relevant_primers.txt

Raw_Folder:
    ../test_data
Data_Folder:
    ../test_data
